line_type_2_name = {
    0x0: ('Roads', 'Road', 'Droga',),
    0x1: ('Roads', 'Motorway', 'Autostrada'),
    0x2: ('Roads', 'Principal highway', 'droga ekspresowa'),
    0x3: ('Roads', 'Principal highway', 'droga krajowa'),
    0x4: ('Roads', 'Arterial Road', 'droga główna'),
    0x5: ('Roads', 'Collector Road', 'droga zbiorcza'),
    0x6: ('Roads', 'Residential street', 'droga lokalna'),
    0x7: ('Roads', 'Alleyway', 'alejka'),
    0x8: ('Roads', 'Highway ramp, low-speed', 'rampa - wolna'),
    0x9: ('Roads', 'Highway ramp, high-speed', 'rampa - szybka'),
    0xa: ('Roads', 'Unpaved', 'droga gruntowa'),
    0xb: ('Roads', 'Highway connector', 'łącznik'),
    0xc: ('Roads', 'Roundabout', 'rondo'),
    0xd: ('Custom', 'Bike route', 'droga dla rowerów'),
    0xe: ('Custom', 'Tunnel', 'tunel'),
    0xf: ('Custom', 'Unpaved road 4x4', 'droga 4x4'),
    0x14: ('Roads', 'Rail road', 'kolej'),
    0x15: ('Water', 'Coast line', 'brzeg'),
    0x16: ('Roads', 'Walkway', 'chodnik/szlak'),
    0x18: ('Water', 'Stream', 'strumień'),
    0x19: ('Boundaries', 'Turn restriction', 'zakaz skretu'),
    0x1a: ('Roads', 'Ferry', 'prom'),
    0x1b: ('Roads', 'Water of rail ferry', 'prom drogowy lub kolejowy'),
    0x1c: ('Boundaries', 'Border', 'granica'),
    0x1d: ('Boundaries', 'Border', 'granica'),
    0x1e: ('Boundaries', 'International boundary', 'granica międzynarodowa'),
    0x1f: ('Water', 'River', 'rzeka'),
}