from PyQt5.QtWidgets import QToolBar, QAction
from PyQt5.QtGui import QIcon
import os.path

class PwMapeditToolbar(QToolBar):
    def __init__(self, title, parent):
        self.actions = {}
        self.icons_folder = os.path.join('icons', 'toolbar_icons')
        super().__init__(title, parent)
        self.actions['save'] = QAction('Zapisz')
        save_icon = QIcon(os.path.join(self.icons_folder, 'save_48.png'))
        self.actions['save'].setIcon(save_icon)
        self.insertAction(None, self.actions['save'])
        self.actions['open'] = QAction('Otwórz')
        self.actions['open'].setIcon(QIcon(os.path.join(self.icons_folder, 'open_48.png')))
        self.insertAction(None, self.actions['open'])
        self.addSeparator()
        self.actions['redo'] = QAction('Redo')
        redo_icon = QIcon(os.path.join(self.icons_folder, 'redo_48.png'))
        self.actions['redo'].setIcon(redo_icon)
        self.insertAction(None, self.actions['redo'])
        self.actions['undo'] = QAction('Undo')
        undo_icon = QIcon(os.path.join(self.icons_folder, 'undo_48.png'))
        self.actions['undo'].setIcon(undo_icon)
        self.insertAction(None, self.actions['undo'])
        self.addSeparator()
        self.actions['cut'] = QAction('Wytnij')
        self.actions['cut'].setIcon(QIcon(os.path.join(self.icons_folder, 'cut_48.png')))
        self.insertAction(None, self.actions['cut'])
        self.actions['copy'] = QAction('Kopiuj')
        self.actions['copy'].setIcon(QIcon(os.path.join(self.icons_folder, 'copy_48.png')))
        self.insertAction(None, self.actions['copy'])
        self.actions['paste'] = QAction('Wklej')
        self.actions['paste'].setIcon(QIcon(os.path.join(self.icons_folder, 'paste_48.png')))
        self.insertAction(None, self.actions['paste'])
        self.addSeparator()
        self.actions['select'] = QAction('Zaznacz')
        self.actions['select'].setIcon(QIcon(os.path.join(self.icons_folder, 'select_48.png')))
        self.insertAction(None, self.actions['select'])
        self.actions['edit_nodes'] = QAction('Edytuj węzły')
        self.actions['edit_nodes'].setIcon(QIcon(os.path.join(self.icons_folder, 'nodes_48.png')))
        self.insertAction(None, self.actions['edit_nodes'])
        self.addSeparator()
        self.actions['create_poi'] = QAction('Utwórz poi')
        self.actions['create_poi'].setIcon(QIcon(os.path.join(self.icons_folder, 'create_poi_48.png')))
        self.insertAction(None, self.actions['create_poi'])
        self.actions['create_polyline'] = QAction('Utwórz polyline')
        self.actions['create_polyline'].setIcon(QIcon(os.path.join(self.icons_folder, 'create_polyline_48.png')))
        self.insertAction(None, self.actions['create_polyline'])
        self.actions['create_polygon'] = QAction('Utwórz polygon')
        self.actions['create_polygon'].setIcon(QIcon(os.path.join(self.icons_folder, 'create_polygon_48.png')))
        self.insertAction(None, self.actions['create_polygon'])
