#!/usr/bin/env python3
# -*- coding: utf-8 -*-

MAP_OBJECT_POI = '[POI]'
MAP_OBJECT_POLYLINE = '[POLYLINE]'
MAP_OBJECT_POLYGON = '[POLYGON]'
MAP_OBJECT_RESTRICT = '[RESTRICT]'
MAP_OBJECT_ROADSIGN = '[SIGN]'
MAP_OBJECT_TYPES = ('[POI]', '[POLYGON]', '[POLYLINE]')
MAP_ALL_OBJECTS = ('[POI]', '[POLYGON]', '[POLYLINE]', '[RESTRICT]', '[SIGN]')
MAP_OBJECT_END = '[END]'
