line_type_2_name = {
    0x0: ('Roads', 'Road', 'Droga',),
    0x1: ('Roads', 'Motorway', 'Autostrada'),
    0x2: ('Roads', 'Principal highway', 'droga ekspresowa'),
    0x3: ('Roads', 'Principal highway', 'droga krajowa'),
    0x4: ('Roads', 'Arterial Road', 'droga główna'),
    0x5: ('Roads', 'Collector Road', 'droga zbiorcza'),
    0x6: ('Roads', 'Residential street', 'droga lokalna'),
    0x7: ('Roads', 'Alleyway', 'alejka'),
    0x8: ('Roads', 'Highway ramp, low-speed', 'rampa - wolna'),
    0x9: ('Roads', 'Highway ramp, high-speed', 'rampa - szybka'),
    0xa: ('Roads', 'Unpaved', 'droga gruntowa'),
    0xb: ('Roads', 'Highway connector', 'łącznik'),
    0xc: ('Roads', 'Roundabout', 'rondo'),
    0xd: ('Custom', 'Bike route', 'droga dla rowerów'),
    0xe: ('Custom', 'Tunnel', 'tunel'),
    0xf: ('Custom', 'Unpaved road 4x4', 'droga 4x4'),
    0x14: ('Roads', 'Rail road', 'kolej'),
    0x15: ('Water', 'Coast line', 'brzeg'),
    0x16: ('Roads', 'Walkway', 'chodnik/szlak'),
    0x18: ('Water', 'Stream', 'strumień'),
    0x19: ('Boundaries', 'Turn restriction', 'zakaz skretu'),
    0x1a: ('Roads', 'Ferry', 'prom'),
    0x1b: ('Roads', 'Water of rail ferry', 'prom drogowy lub kolejowy'),
    0x1c: ('Boundaries', 'Border', 'granica'),
    0x1d: ('Boundaries', 'Border', 'granica'),
    0x1e: ('Boundaries', 'International boundary', 'granica międzynarodowa'),
    0x1f: ('Water', 'River', 'rzeka'),
    0x20: ('Elevation', 'Minor land contour (1/10)', ''),
    0x21: ('Elevation', 'Interm. land contour (1/2)', ''),
    0x22: ('Elevation', 'Major land contour (1/1)', ''),
    0x23: ('Elevation', 'Minor depth contour (1/10)', ''),
    0x24: ('Elevation', 'Interm. depth contour (1/2)', ''),
    0x25: ('Elevation', 'Major depth contour (1/1)', ''),
    0x26: ('Water', 'Intermittenth stream/ditch', ''),
    0x27: ('Man made', 'Airport runway centerline', 'pas startowy linia centralna'),
    0x28: ('Man made', 'Oil or water pipeline', 'rurociąg ropa/woda'),
    0x29: ('Man made', 'Powerline', 'linia energetyczna'),
    0x2a: ('Water', 'Marine boundary', 'granica morska'),
    0x2b: ('Water', 'Marine hazard', 'granica morska niebezpieczeństwo'),
    0x2f: ('Custom', 'Road sign', 'podpowiedź'),
    0x10e00: ('Custom', 'Hiking trial red', 'Szlak pieszy czerwony'),
    0x10e01: ('Custom', 'Hiking trial yellow', 'Szlak pieszy żółty'),
    0x10e02: ('Custom', 'Hiking trial green', 'Szlak pieszy zielony'),
    0x10e03: ('Custom', 'Hiking trial blue', 'Szlak pieszy niebieski'),
    0x10e04: ('Custom', 'Hiking trial black', 'Szlak pieszy czarny'),
    0x10e05: ('Custom', 'dirindicator', 'rezerwacja-nakladka'),
    0x10e06: ('Custom', 'no Car', 'rezerwacja-nakladka'),
    0x10e07: ('Custom', 'Hiking trial multi', 'Szlak pieszy kolorowy'),
    0x10e08: ('Custom', 'Bike trial red', 'Szlak rowerowy czerwony'),
    0x10e09: ('Custom', 'Bike trial yellow', 'Szlak rowerowy żółty'),
    0x10e0a: ('Custom', 'Bike trial green', 'Szlak rowerowy zielony'),
    0x10e0b: ('Custom', 'Bike trial blue', 'Szlak rowerowy niebieski'),
    0x10e0c: ('Custom', 'Bike trial black', 'Szlak rowerowy czarny'),
    0x10e0d: ('Custom', 'Bike trial other', 'Szlak rowerowy inny'),
    0x10e0f: ('Custom', 'Trial other', 'Szlak inny'),
    0x10e10: ('Custom', 'Tram', 'tramwaj'),
    0x10e11: ('Custom', 'Planned', 'planowana ulica'),
    0x10e12: ('Custom', 'Planned', 'planowana droga'),
    0x10e13: ('Custom', 'Under construction', 'w budowie'),
    0x10e14: ('Custom', 'Railroad', 'kolej'),
    0x10e15: ('Custom', 'Railroad underground', 'kolej podziemna/rozebrana'),
    0x10e16: ('Custom', 'Ski lift', 'wyciąg/kolejka'),
    0x10e17: ('Custom', 'Ski lift', 'wyciąg/orczyk'),
    0x10e1a: ('Custom', 'Floodbank', 'wał przeciwpowodziowy'),
    0x10e1b: ('Custom', 'Walls', 'mury'),
    0x10e1c: ('Custom', 'border PN/PK', 'granica PN/PK'),
    0x10f1a: ('Custom', 'Pier', 'pirs'),
    0x10f1b: ('Custom', 'Underwater pipe', 'rurociąg podwodny'),
    0x10f1c: ('Custom', 'Underwater cable', 'kabel podwodny'),
    0x10f1d: ('Custom', 'recommended track', 'zalecana trasa'),
    0x10f1e: ('Custom', 'Leading line', 'linia nabieżnika'),
    0x10f1f: ('Custom', 'Separation line', 'linia rozgraniczenia'),
}

polygon_type_2_name = {
    0x1: ('Cities', 'City', 'miasto duże powyżej 200tys'),
    0x2: ('Cities', 'City', 'miasto małe'),
    0x3: ('Cities', 'Rural housing area', 'obszar zamieszkały'),
    0x4: ('Man made', 'Military base', 'baza wojskowa'),
    0x5: ('Man made', 'Parking', 'parking odkryty'),
    0x6: ('Man made', 'Parking garage', 'parking pod dachem'),
    0x7: ('Man made', 'Airport', 'terminal lotniska lub hangar'),
    0x8: ('Man made', 'Shop', 'sklep'),
    0x9: ('Man made', 'Marina', 'porty przystanie terminale kontererowe'),
    0xa: ('Man made', 'School', 'szkola'),
    0xb: ('Man made', 'Hospital', 'szpital'),
    0xc: ('Man made', 'Industrial area', 'teren przemysłowy'),
    0xd: ('Man made', 'Reservation', ''),
    0xe: ('Man made', 'Airport runway', 'pas startowy'),
    0x13: ('Building', 'Building', 'budynek'),
    0x14: ('Land', 'Forest', 'las'),
    0x15: ('Land', 'National park', 'park narodowy rezerwat'),
    0x16: ('Land', 'National park', ''),
    0x17: ('Man made', 'City park', 'park miejski'),
    0x18: ('Sports', 'Golf course', 'pole golfowe'),
    0x19: ('Sports', 'Sports comples', 'obiekty sportowe'),
    0x1a: ('Man made', 'Cemetery', 'cmentarz'),
    0x1e: ('Land', 'State park', ''),
    0x1f: ('Land', 'State park', ''),
    0x20: ('Land', 'State park', ''),
    0x28: ('Water', 'Sea/Ocean', ''),
    0x29: ('Water', 'Blue-unknown', ''),
    0x32: ('Water', 'Sea', 'morze'),
    0x3b: ('Water', 'Blue-unknown', ''),
    0x3c: ('Water', 'Large lake', 'duże jezioro'),
    0x3d: ('Water', 'Large lake', 'duże jezioro'),
    0x3e: ('Water', 'Medium lake', 'średnie jezioro'),
    0x3f: ('Water', 'Medium lake', 'średnie jezioro'),
    0x40: ('Water', 'Small lake', 'małe jezioro'),
    0x41: ('Water', 'Small lake', 'małe jezioro'),
    0x42: ('Water', 'Major lake (>3.3 tkm2)', ''),
    0x43: ('Water', 'Major lake (1.1-3.3 tkm2)', ''),
    0x44: ('Water', 'Large lake (0.6-1.1 tkm2)', ''),
    0x45: ('Water', 'Blue-unknown', ''),
    0x46: ('Water', 'Major river', 'duża rzeka (rozlewisko)'),
    0x47: ('Water', 'Large river', 'duża rzeka'),
    0x48: ('Water', 'Medium river', 'średnia rzeka'),
    0x49: ('Water', 'Small river', 'mała rzeka'),
    0x4a: ('Other', 'Map selection area', ''),
    0x4b: ('Other', 'Map coverage area', ''),
    0x4c: ('Water', 'Drying or salt pan', 'osuch lub salina'),
    0x4d: ('Land', 'Glacier', 'lodowiec'),
    0x4e: ('Man made', 'Orchard', 'sad i ogrody działkowe'),
    0x4f: ('Land', 'Scrub', 'zarośla i nieużytki'),
    0x50: ('Land', 'Don\'t use! See 0x14', 'Nie używać! Las jest 0x14'),
    0x51: ('Water', 'Swamp', 'mokradła'),
    0x52: ('Land', 'Tundra', ''),
    0x53: ('Water', 'Sand', 'piach wydmy i wysypiska'),
    0x1101e: ('Cusom', 'Separation zone', 'strefa rozgraniczenia'),
    0x1101f: ('Cusom', 'Separation zone', 'strefa rozgraniczenia')
}