type_2_alias = {
            '0x0600': ["poi_large_citi", "poi_major_citi"],
            '0x0b00': ["city", "geo_name_man", "poi_small_citi"],
            '0x0d00': ["poi_med_cities"],
            '0x1300': ["przystan"],
            '0x1400': ["wp_dot"],
            '0x1605': ["mapa"],
            '0x1606': ["stawa"],
            '0x1607': ["bezp_woda"],
            '0x1608': ["lewa"],
            '0x1609': ["prawa"],
            '0x160a': ["nieb_odosobn"],
            '0x160b': ["specjalna"],
            '0x160c': ["kardynalna"],
            '0x160d': ["inna"],
            '0x160f': ["biale"],
            '0x1610': ["czerwone"],
            '0x1611': ["zielone"],
            '0x1612': ["zolte"],
            '0x1613': ["pomaranczowe"],
            '0x1614': ["fioletowe"],
            '0x1615': ["niebieskie"],
            '0x1616': ["wielobarwne"],
            '0x1709': ["wiadukt"],
            '0x1708': ["slepy"],
            '0x170a': ["weryfikowac"],
            '0x170b': ["uwaga"],
            '0x170d': ["watpliwy", "nie_wiem"],
            '0x1710': ["zakaz"],
            '0x1711': ["sprawdz"],
            '0x1712': ["remont"],
            '0x1805': ["signstat"],
            '0x1806': ["stawa_r"],
            '0x1807': ["stawa_by", "stawa_pn"],
            '0x1808': ["prawa_b"],
            '0x1809': ["lewa_b"],
            '0x180a': ["stawa_brb", "stawa_nieb"],
            '0x180b': ["boja"],
            '0x180d': ["w_prawo"],
            '0x180c': ["kard_n"],
            '0x1905': ["tablica"],
            '0x1906': ["stawa_g"],
            '0x1907': ["stawa_yb", "stawa_pd"],
            '0x1908': ["stawa_rgr"],
            '0x1909': ["stawa_grg"],
            '0x190a': ["stawa_rwr"],
            '0x190b': ["dalba"],
            '0x190c': ["kard_s"],
            '0x190d': ["w_lewo"],
            '0x1a06': ["stawa_y"],
            '0x1a07': ["stawa_byb", "stawa_ws"],
            '0x1a08': ["stawa_rw"],
            '0x1a09': ["stawa_gw"],
            '0x1a0a': ["stawa_bw"],
            '0x1a0c': ["kard_e"],
            '0x1a0d': ["w_lewo_b"],
            '0x1b06': ["stawa_w"],
            '0x1b07': ["stawa_yby", "stawa_za"],
            '0x1b08': ["stawa_wr"],
            '0x1b09': ["stawa_wg"],
            '0x1b0a': ["stawa_wb"],
            '0x1b0b': ["stawa_b"],
            '0x1b0c': ["kard_w"],
            '0x1b0d': ["w_prawo_b"],
            '0x1c01': ["wrak_wid"],
            '0x1c02': ["wrak"],
            '0x1c03': ["wrak_bezp"],
            '0x1c04': ["wrak_tral"],
            '0x1c05': ["glaz_wid"],
            '0x1c07': ["przeszkoda"],
            '0x1c08': ["przeszkoda_tral"],
            '0x1c09': ["glaz_zal"],
            '0x1c0a': ["glaz"],
            '0x1c0b': ["obiekt"],
            '0x1f00': ["rejon"],
            '0x2000': ["zjazd"],
            '0x2500': ["oplata"],
            '0x2700': ["exit"],
            '0x2800': ["dzielnica", "label", "kwatera", "adr", "housenumber"],
            '0x2a00': ["jedzenie"],
            '0x2a01': ["american"],
            '0x2a02': ["asian", "sushi"],
            '0x2a03': ["kebab", "barbecue", "grill"],
            '0x2a04': ["chinese"],
            '0x2a05': ["deli", "piekarnia"],
            '0x2a06': ["restauracja", "internationa", "international", "restaurant"],
            '0x2a07': ["fastfood", "food", "burger"],
            '0x2a08': ["italian"],
            '0x2a09': ["mexican"],
            '0x2a0a': ["pizza"],
            '0x2a0b': ["seafood"],
            '0x2a0c': ["steak"],
            '0x2a0d': ["cukiernia", "bagel"],
            '0x2a0e': ["kawiarnia", "cafe", "caffe", "coffee"],
            '0x2a0f': ["french"],
            '0x2a10': ["german"],
            '0x2a11': ["british"],
            '0x2a12': ["mleczny", "vegetarian", "glutenfree"],
            '0x2a13': ["grecka", "libanska", "greek"],
            '0x2b00': ["schronisko", "hostel"],
            '0x2b01': ["hotel", "lodging", "motel"],
            '0x2b02': ["b&b", "agro", "nocleg"],
            '0x2b03': ["camping", "polenamiot"],
            '0x2b04': ["resort"],
            '0x2c00': ["atrakcja"],
            '0x2c01': ["plac_zabaw", "amusement_park"],
            '0x2c02': ["muzeum", "galeria", "museum", "muzea"],
            '0x2c03': ["biblioteka", "video"],
            '0x2c04': ["zamek", "castle", "palac", "dworek"],
            '0x2c05': ["szkola", "zlobek", "przedszkole", "school", "szkoly", "gimnazjum", "liceum", "uczelnia"],
            '0x2c06': ["park"],
            '0x2c07': ["zoo"],
            '0x2c08': ["stadion", "stadium"],
            '0x2c09': ["targi", "fair"],
            '0x2c0a': ["winiarnia", "winery", "browar", "brewery"],
            '0x2c0b': ["kosciol", "kaplica", "cerkiew", "synagoga", "meczet", "gompa", "mandir", "stupa", "czorten"],
            '0x2c10': ["mural"],
            '0x2d00': ["esc_room"],
            '0x2d01': ["kultura", "teatr", "teatry", "theater"],
            '0x2d02': ["bar", "mug", "pub"],
            '0x2d03': ["kino", "kina", "multikino"],
            '0x2d04': ["kasyno", "casino"],
            '0x2d05': ["golf"],
            '0x2d06': ["narty"],
            '0x2d07': ["kregle", "bowling"],
            '0x2d08': ["lodowisko"],
            '0x2d09': ["basen", "baseny", "nurek"],
            '0x2d0a': ["sport", "fitness", "kort", "korty", "skatepark", "boisko"],
            '0x2d0b': ["ladowisko", "landing"],
            '0x2e00': ["sklep", "books", "ksiegarnia", "shop", "special", "specialty"],
            '0x2e01': ["hala", "dept", "store", "market"],
            '0x2e02': ["bazar", "grocery", "spozywczy"],
            '0x2e03': ["super", "supermarket"],
            '0x2e04': ["hiper", "shopping_cart", "sklepy"],
            '0x2e05': ["apteka", "apteki", "pharmacy"],
            '0x2e06': ["24h", "fuel_store"],
            '0x2e07': ["ubrania"],
            '0x2e08': ["budowlane", "budowlany", "dom_i_ogrod"],
            '0x2e09': ["meble", "wnetrza"],
            '0x2e0a': ["rowerowy", "sportowy", "turystyczny"],
            '0x2e0b': ["rtv", "komputery"],
            '0x2f01': ["benzyna", "fuel", "lpg", "cng", "stacje", "paliwo", "elektryczne", "bp", "prad", "wodor"],
            '0x2f02': ["rentacar", "rent_a_bike", "rowery", "rent_a_boat", "lodki"],
            '0x2f03': ["auto", "car", "carrepair", "carservice"],
            '0x2f04': ["lotnisko", "airport"],
            '0x2f05': ["poczta", "inpost", "paczkomat", "kurier"],
            '0x2f06': ["atm", "atmbank", "bank", "banki", "kantor"],
            '0x2f07': ["cardealer"],
            '0x2f08': ["bus", "metro", "pkp", "pks", "tram", "taxi"],
            '0x2f09': ["port", "marina", "stanica"],
            '0x2f0b': ["parking"],
            '0x2f0c': ["info", "informacja"],
            '0x2f0d': ["autoklub", "tor"],
            '0x2f0e': ["myjnia", "carwash"],
            '0x2f0f': ["garmin"],
            '0x2f10': ["uslugi", "tatoo", "optyk", "fryzjer", "lombard"],
            '0x2f11': ["fabryka"],
            '0x2f12': ["wifi", "hotspot"],
            '0x2f13': ["serwis", "repair", "naprawa"],
            '0x2f14': ["pralnia", "social"],
            '0x2f15': ["budynek", "building"],
            '0x2f16': ["truck_stop"],
            '0x2f17': ["turystyka"],  # ","biuro","turystyczne,","transit_services
            '0x2f18': ["biletomat"],
            '0x2f1b': ["business", "firma"],
            '0x3000': ["emergency"],
            '0x3001': ["policja"],
            '0x3002': ["dentysta", "pogotowie", "przychodnia", "szpital", "szpitale", "uzdrowisko",
                       "weterynarz", "aed"],
            '0x3003': ["ratusz"],
            '0x3004': ["sad", "areszt", "wiezienie","zaklad_karny"],
            '0x3005': ["koncert", "concert", "hall"],
            '0x3006': ["border", "toll"],
            '0x3007': ["urzad", "instytucje", "prokuratura"],
            '0x3008': ["pozarna"],
            '0x4100': ["ryba"],
            '0x4300': ["kotwicowisko"],
            '0x4700': ["slip", "boat_ramp"],
            '0x4a00': ["picnic", "rest", "restroom"],
            '0x4f00': ["prysznic", "shower"],
            '0x5a00': ["km"],
            '0x5a01': ["slupek_granica", "slupek"],
            '0x5a02': ["km_woda"],
            '0x5100': ["telefon", "sos"],
            '0x5200': ["widok", "scenic"],
            '0x5300': ["skiing", "ski"],
            '0x5400': ["kapielisko"],
            '0x5600': ["fa", "fp", "fs", "fo", "kd", "ra", "po", "rl", "fotoradar", "radar"],
            '0x5700': ["czarnypunkt", "danger", "nm", "pk", "spk", "npk", "op"],
            '0x5800': ['REP_N-S'],
            '0x5801': ['REP_E-W'],
            '0x5802': ['REP_NW-SE'],
            '0x5803': ['REP_NE-SW'],
            '0x5804': ['REP_N'],
            '0x5805': ['REP_S'],
            '0x5806': ['REP_E'],
            '0x5807': ['REP_W'],
            '0x5808': ['REP_NW'],
            '0x5809': ['REP_NE'],
            '0x580a': ['REP_SW'],
            '0x580b': ['REP_SE'],
            '0x5901': ["airportbig"],
            '0x5902': ["airportmed", "lotnisko_srednie"],
            '0x5903': ["airportsmall", "lotnisko_male", "aeroklub"],
            '0x5904': ["heli"],
            '0x593f': ["transport"],
            '0x5e00': ["wozek"],
            '0x5f00': ["trafo"],
            '0x6100': ["bunkier"],
            '0x6101': ["ruiny"],
            '0x6200': ["glebokosc"],
            '0x6300': ["wysokosc"],
            '0x6400': ["pomnik", "zabytek"],
            '0x6401': ["most", "bridge"],
            '0x6402': ["dom", "house"],
            '0x6403': ["cmentarz", "cemetery", "kirkut", "mizar"],
            '0x6404': ["krzyz", "kapliczka"],
            '0x6405': ["lesniczowka"],
            '0x6406': ["crossing", "prom"],
            '0x6407': ["tama"],
            '0x6409': ["jaz"],
            '0x640a': ["kamera", "webcam"],
            '0x640b': ["wojsko"],
            '0x640c': ["kopalnia"],
            '0x640d': ["platforma"],
            '0x640e': ["rezerwat", "rv_park"],
            '0x640f': ["postbox"],
            '0x6411': ["wieza", "short_tower", "tall_tower", "tower"],
            '0x6412': ["szlak", "trail"],
            '0x6413': ["tunel", "cave", "jaskinia"],
            '0x6414': ["oligocen"],
            '0x6415': ["fort"],
            '0x6502': ["brod"],
            '0x6503': ["zatoka"],
            '0x6505': ["canal"],
            '0x6506': ["river"],
            '0x6508': ["wodospad"],
            '0x6509': ["fontanna"],
            '0x650a': ["lodowiec"],
            '0x650d': ["jezioro"],
            '0x650f': ["wc", "toitoi"],
            '0x6511': ["zrodlo", "spring"],
            '0x6512': ["stream"],
            '0x6513': ["pond"],
            '0x6600': ["kurhan"],
            '0x6602': ["obszar", "area"],
            '0x6604': ["kapielisko", "plaza"],
            '0x6605': ["sluza"],
            '0x6606': ["przyladek"],
            '0x6607': ["urwisko"],
            '0x660a': ["drzewo", "tree"],
            '0x660f': ["wiatrak"],
            '0x6610': ["elevation", "plain"],
            '0x6614': ["skala"],
            '0x6616': ["gora", "hill", "mountain", "mountains", "przelecz", "summit"],
            '0x6617': ["dolina"],
            '0xf201': ["swiatla"],
            '0x6701': ["szlak_g"],
            '0x6702': ["szlak_r"],
            '0x6703': ["szlak_b"],
            '0x6704': ["szlak_y"],
            '0x6705': ["szlak_k"],
            '0x6707': ["rower_g"],
            '0x6708': ["rower_r"],
            '0x6709': ["rower_b", "premia"],
            '0x670a': ["rower_y"],
            '0x670b': ["rower_k"],
}